version: '3.8'
services:
  app:
    image: wncc
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "9006:3000"