import { initializeApp } from "firebase/app";
import { getMessaging, getToken } from "firebase/messaging";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

const firebaseConfig = {
  apiKey: "AIzaSyBq64HWdfk5p47V7yJtHvRP1_mflsrnqlY",
  authDomain: "authmodule-test.firebaseapp.com",
  databaseURL: "https://authmodule-test-default-rtdb.firebaseio.com",
  projectId: "authmodule-test",
  storageBucket: "authmodule-test.appspot.com",
  messagingSenderId: "239733814657",
  appId: "1:239733814657:web:08d8a08350060cbe1ea480",
  measurementId: "G-WQMCS66HE7"
};

initializeApp(firebaseConfig);

const Home: NextPage = () => {
  const [token, setToken] = useState<string>("");
  async function getFCMToken() {
    const messaging = getMessaging();

    try {
      // Don't forget to paste your VAPID key here
      // (you can find it in the Console too)
      const token = await getToken(messaging, {
        vapidKey:
          "BHwMNMm1xxi1ziF9-extqVPj4KL9Rn8yNUbDE2pP8bTzkOXMd-wm88Sbycso-5yMyhacqgAJfDDp8jcR2FLMxy8",
      });
      console.log("TOKEN :", token);
      setToken(token);
      return token;
    } catch (e) {
      console.log("getFCMToken error", e);
      return undefined;
    }
  }

  useEffect(() => {
    getFCMToken();
  }, []);
  return (
    <div className={styles.container}>
      <p>Hosssssssssss</p>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          width: "80%",
        }}
      >
        <p>{token}</p>
      </div>
    </div>
  );
};

export default Home;
