import { initializeApp } from "firebase/app";
import { getMessaging, getToken } from "firebase/messaging";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

const firebaseConfig = {
  apiKey: "AIzaSyBfTuzIZ19EWIE5BVGseKifa_4iuITXEvk",
  authDomain: "test-6393f.firebaseapp.com",
  projectId: "test-6393f",
  storageBucket: "test-6393f.appspot.com",
  messagingSenderId: "428344922618",
  appId: "1:428344922618:web:159fa46538cbbbf6d39443",
  measurementId: "G-W596FW4R3C"
};

initializeApp(firebaseConfig);

const Home: NextPage = () => {
  const [token, setToken] = useState<string>("");
  async function getFCMToken() {
    const messaging = getMessaging();

    try {
      // Don't forget to paste your VAPID key here
      // (you can find it in the Console too)
      const token = await getToken(messaging, {
        vapidKey:
          "BK_kmEAr9yzQHm5PsgUneXLZTnJMsV-HmYjQeOrgz6QGKszLWtSeLNo-dUTolW4TqIkGtj0spOXFLRsA9rWnlRw",
      });
      console.log("TOKEN :", token);
      setToken(token);
      return token;
    } catch (e) {
      console.log("getFCMToken error", e);
      return undefined;
    }
  }

  useEffect(() => {
    getFCMToken();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          width: "80%",
        }}
      >
        <p>{token}</p>
      </div>
    </div>
  );
};

export default Home;
