import { initializeApp } from "firebase/app";
import { getMessaging, getToken } from "firebase/messaging";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

const firebaseConfig = {
  apiKey: "AIzaSyCsf_zMJxfBzMhlKUi_orLQ5Hnb-567VeM",
  authDomain: "remah-a60ee.firebaseapp.com",
  projectId: "remah-a60ee",
  storageBucket: "remah-a60ee.appspot.com",
  messagingSenderId: "693802205955",
  appId: "1:693802205955:web:b1f8a89e5dc36f84331f36",
  measurementId: "G-RLGY9PRJK3"
};

initializeApp(firebaseConfig);

const Home: NextPage = () => {
  const [token, setToken] = useState<string>("");
  async function getFCMToken() {
    const messaging = getMessaging();

    try {
      // Don't forget to paste your VAPID key here
      // (you can find it in the Console too)
      const token = await getToken(messaging, {
        vapidKey:
          "BO79Cq0EYWj7IIWRoenWUpcTXjJEfbKa-pXphgm4aXkeKYOi1ehOIeKIIAsOEO_gfovroeKBaC1ESBpPul33Oec",
      });
      console.log("TOKEN :", token);
      setToken(token);
      return token;
    } catch (e) {
      console.log("getFCMToken error", e);
      return undefined;
    }
  }

  useEffect(() => {
    getFCMToken();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          width: "80%",
        }}
      >
        <p>{token}</p>
      </div>
    </div>
  );
};

export default Home;
